---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
  language_info:
    codemirror_mode:
      name: ipython
      version: 3
    file_extension: .py
    mimetype: text/x-python
    name: python
    nbconvert_exporter: python
    pygments_lexer: ipython3
    version: 3.6.5
---

---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
  language_info:
    codemirror_mode:
      name: ipython
      version: 3
    file_extension: .py
    mimetype: text/x-python
    name: python
    nbconvert_exporter: python
    pygments_lexer: ipython3
    version: 3.6.5
---

# Random choice

```{python}
# Import the array library
import numpy as np
# Make random number generator.
rng = np.random.default_rng()
```

We are building up to an answer to the [three girls
problem](../code-basics/three_girls).  At the end of the [lists
page](../data-types/lists), we found a way to simulate one family, and get a
count.

Up until now, we have simulated each child in the family by randomly choosing
an integer from 0 up to, but not including 2.  Therefore, we are randomly
choosing between 0 and 1, like this.

```{python}
one_child = rng.integers(0, 2)
one_child
```

Now we know about function arguments, lists and arrays, we can use a nicer alternative to do the same thing — `rng.choice`.

The `choice` method of the Numpy random generator object asks Numpy to choose
from the choices you sent it, at random.

For example, say we want the `rng` to choose randomly between 0 and 1, we could do this:

```{python}
# Choose randomly between 0 and 1.
choices = [0, 1]
rng.choice(choices)
```

By default, the `choice` method chooses at random from the choice you give,
return each choice with the same probability.   In our case, it is returning 0
with probability 0.5 and 1 with probability 0.5.

However, you can use the `p` keyword argument to tell the function the probabilities to use for each choice.

For example, let us return to the [supreme court jury
problem](../code-basics/sampling_problem).  Remember, we wanted to simulate a jury of 12 people, where each juror has a 26% chance of being Black.

We use 1 to mean Black, and 0 to mean White.

Now we want to select 1 (Black) with probability 0.26 (26%) and 0 (White) with
probability 1 - 0.26 = 0.74.  The `p` keyword argument to `choice` allows us to
do that:

```{python}
# Select Black with probability 0.26, White with probability 0.74.
rng.choice(choices, p=[0.26, 0.74])
```

Run the cell above a few times to persuade yourself that you see 1 about
quarter of the time, and 0 otherwise.

The `choice` method has another useful keyword argument, `size`.  We can use this to ask `choice` to make multiple choices at the same time.  `choice` returns the choices as an array.  For example, say we wanted to choose 12 jurors, each with a probability of 0.26 of being 1 (Black).  We could do this:

```{python}
# Select 12 jurors in one go.
rng.choice(choices, p=[0.26, 0.74], size=12)
```

Now consider the problem of choosing 4 children, each with a probability of 0.5
of being a Girl.  Let's do the same as we did before, and use 0 for a boy, and
1 for girl.

```{python}
sexes = [0, 1]
children = rng.choice(sexes, p=[0.5, 0.5], size=4)
children
```

Notice that the default is for `choice` to give equal probability the given choices, so, in this case, we can simply miss out the `p=[0.5, 0.5]` argument and get the same outcome:

```{python}
# choice selects each option with the same probability unless told otherwise.
children = rng.choice(sexes, size=4)
children
```
