---
jupyter:
  jupyterbook:
    show_stderr: true
  jupytext:
    formats: ''
    notebook_metadata_filter: all,-language_info
    split_at_heading: true
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.14.1
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

# Sorting DataFrames

```{python}
# Load the Pandas data science library, call it 'pd'
import pandas as pd
# Turn on a setting to use Pandas more safely.
# We will discuss this setting later.
pd.set_option('mode.copy_on_write', True)

# Load the library for plotting, name it 'plt'
import matplotlib.pyplot as plt
# Make plots look a little more fancy
plt.style.use('fivethirtyeight')
```

In [basic row indexing](df_basic_row_indexing.Rmd) we found the slightly odd
result that, for rich countries, there is little relationship between GDP and
maternal mortality.

```{python}
# Original data frame before dropping missing values.
gender_data = pd.read_csv('gender_stats.csv')
gender_data_no_na = gender_data.dropna()
labeled_gdata = gender_data_no_na.set_index('country_code')
# Select the rich countries
gdp = labeled_gdata['gdp_us_billion']
rich_gender_data = labeled_gdata[gdp > 1000]
rich_gender_data
```

```{python}
plt.scatter(rich_gender_data['gdp_us_billion'],
            rich_gender_data['mat_mort_ratio'])
plt.title('Maternal mortality ratio as a function of GDP')
```

One thing that stands out is the very high value at around 180.   Which country
does this refer to?  We can use sorting to find out.

Data frames have a method `sort_value`.  This returns a new data frame with the
rows sorted by the values in the column we specify.

Here are the first five rows of the data frame of the rich countries:

```{python}
rich_gender_data.head()
```

We are interested to find which of these richer countries has a high maternal
mortality ratio.  To do this, we can make a new data frame where the rows are
sorted by the values in the `mat_mort_ratio` column:

```{python}
rich_by_mmr = rich_gender_data.sort_values('mat_mort_ratio')
rich_by_mmr.head()
```

Notice that the rows are in *ascending* order of `mat_mort_ratio`.  To find the countries with high maternal mortality, we might prefer to sort in *descending* order.  As usual you can explore how
you might do this by looking at the help for the `sort_values` method with:

```
rich_by_mmr.sort_values?
```

in a new cell.   If you do that, you discover the `ascending` argument, that
you can use like this:

```{python}
rich_by_descending_mmr = rich_gender_data.sort_values('mat_mort_ratio', ascending=False)
rich_by_descending_mmr.head()
```

As you might have guessed by now, `Series` also have a `sort_values` method.
For a Series, you don't have to specify the column to sort from, because you
are using the Series values.

```{python}
rich_mmr = rich_gender_data['mat_mort_ratio']
type(rich_mmr)
```

```{python}
rich_mmr.sort_values(ascending=False)
```

To investigate further, we need to do some calculations to adjust for the
population.
