---
jupyter:
  jupyterbook:
    show_stderr: true
  jupytext:
    formats: ''
    notebook_metadata_filter: all,-language_info
    split_at_heading: true
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.14.1
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

# Calculations using Series

```{python}
# Load the Pandas data science library, call it 'pd'
import pandas as pd
# Turn on a setting to use Pandas more safely.
# We will discuss this setting later.
pd.set_option('mode.copy_on_write', True)

# Load the library for plotting, name it 'plt'
import matplotlib.pyplot as plt
# Make plots look a little more fancy
plt.style.use('fivethirtyeight')
```

In [data frame sorting](df_sorting.Rmd) we found the slightly odd result that,
for rich countries, there is little relationship between GDP and maternal
mortality.

We start with the rows restricted to rich countries, and sorted by maternal
mortality ratio.

```{python}
# Original data frame before dropping missing values.
gender_data = pd.read_csv('gender_stats.csv')
gender_data_no_na = gender_data.dropna()
labeled_gdata = gender_data_no_na.set_index('country_code')
# Select the rich countries
gdp = labeled_gdata['gdp_us_billion']
rich_gender_data = labeled_gdata[gdp > 1000]
rich_by_descending_mmr = rich_gender_data.sort_values('mat_mort_ratio', ascending=False)
rich_by_descending_mmr.head()
```

The question of interest is, why does there appear to be so little relationship
between the GDP and the maternal mortality ratio.

We considered whether the lack of relationship was because the key question is
how much money the country spends per person.  We need to do some calculations
to investigate.

We can calculate with Pandas Series, just as we can with arrays.

For example, now we know that India has both a high GDP, and a high maternal mortality ratio, we wonder whether this is because India also has a large population, and therefore, relatively little money per person to spend on health care.

So, we would like know the GDP per capita.  Luckily the data frame as a column
"population":

```{python}
rich_population = rich_by_descending_mmr["population"]
rich_population
```

We can divide the GDP by the population in millions to get US billion dollars per million population.

This works exactly as it does for arrays:

```{python}
rich_gdp = rich_by_descending_mmr["gdp_us_billion"]
rich_gdp
```

```{python}
gdp_per_million = rich_gdp / rich_population
gdp_per_million
```

Notice that the result is *elementwise* division.  Python divides each element
in `rich_gdp` by the *corresponding* element in `rich_population`.


Remember that India is the first country in the `rich_by_descending_mmr`
data frame.  It also has by far the lowest GDP per million population of
any of this selection of rich countries.   Here's a plot of
`gdp_per_million` against the corresponding values in `mat_mort_ratio`:

```{python}
plt.scatter(gdp_per_million, rich_by_descending_mmr['mat_mort_ratio'])
```

It does look as if low income per person predisposes to high maternal mortality.
